<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wav"
    nsURI="http:///com/skratchdot/riff/wav/RIFFWave.ecore" nsPrefix="com.skratchdot.riff.wav">
  <eClassifiers xsi:type="ecore:EClass" name="RIFFWave">
    <eOperations name="getChunksByEClass">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments eClassifier="#//Chunk"/>
      </eGenericType>
      <eParameters name="eClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="getFirstChunkByEClass" eType="#//Chunk">
      <eParameters name="eClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="init" eExceptions="#//RiffWaveException">
      <eParameters name="buf" eType="#//ExtendedByteBuffer"/>
    </eOperations>
    <eOperations name="toAudioFileFormat" eType="#//AudioFileFormat" eExceptions="#//UnsupportedAudioFileException"/>
    <eOperations name="toAudioFormat" eType="#//AudioFormat" eExceptions="#//UnsupportedAudioFileException"/>
    <eOperations name="toAudioInputStream" eType="#//AudioInputStream" eExceptions="#//UnsupportedAudioFileException"/>
    <eOperations name="toByteArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"
        eExceptions="#//RiffWaveException"/>
    <eOperations name="write" eExceptions="#//IOException #//RiffWaveException">
      <eParameters name="file" eType="#//File"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chunks" upperBound="-1"
        eType="#//Chunk" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parseChunkExceptions" upperBound="-1"
        eType="#//ParseChunkException" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampleData" eType="#//SampleData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chunk" abstract="true">
    <eOperations name="init" eExceptions="#//RiffWaveException">
      <eParameters name="riffWave" eType="#//RIFFWave"/>
      <eParameters name="buf" eType="#//ExtendedByteBuffer"/>
    </eOperations>
    <eOperations name="toByteArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"
        eExceptions="#//RiffWaveException"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockAlignedSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chunkTypeID" eType="#//ChunkTypeID"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chunkTypeIDValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkCue" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfCuePoints" eType="#//UnsignedInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cuePoints" upperBound="-1"
        eType="#//CuePoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkData" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampleDataOriginal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkDataList" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeID" eType="#//ChunkDataListTypeID"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataListChunks" upperBound="-1"
        eType="#//ChunkDataListType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkDataListType" abstract="true" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cuePointID" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textAsString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkDataListTypeLabel" eSuperTypes="#//ChunkDataListType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkDataListTypeLabeledText" eSuperTypes="#//ChunkDataListType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampleLength" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purposeID" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="country" eType="#//UnsignedShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="#//UnsignedShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dialect" eType="#//UnsignedShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codePage" eType="#//UnsignedShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkDataListTypeNote" eSuperTypes="#//ChunkDataListType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkFact" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatDependantData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkFormat" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compressionCode" eType="#//CompressionCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compressionCodeValue" eType="#//UnsignedShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfChannels" eType="#//UnsignedShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampleRate" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageBytesPerSecond"
        eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockAlign" eType="#//UnsignedShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="significantBitsPerSample"
        eType="#//UnsignedShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfExtraFormatBytes"
        eType="#//UnsignedShort" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraFormatBytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkInstrument" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unshiftedNote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fineTune" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowNote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highNote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowVelocity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highVelocity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkPlayList" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSegments" eType="#//UnsignedInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Segment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkSampler" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manufacturer" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="product" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="samplePeriod" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="midiUnityNote" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="midiPitchFraction" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smpteFormat" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smpteOffset" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSampleLoops" eType="#//UnsignedInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="samplerDataSize" eType="#//UnsignedInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sampleLoops" upperBound="-1"
        eType="#//SampleLoop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="samplerData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkSilent" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSilentSamples"
        eType="#//UnsignedInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkUnknown" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unknownChunkTypeIdValue"
        eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wavRandomAccessFilePointer"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChunkWaveList" eSuperTypes="#//Chunk">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternatingSilentAndDataChunks"
        upperBound="-1" eType="#//Chunk" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CuePoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cuePointID" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataChunkID" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chunkStart" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockStart" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sampleOffset" eType="#//UnsignedInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParseChunkException">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exception" eType="#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringCause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringStackTrace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampleData" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SampleData8Bit" eSuperTypes="#//SampleData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sample" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampleData16Bit" eSuperTypes="#//SampleData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sample" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampleLoop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cuePointID" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="playCount" eType="#//UnsignedInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cuePointID" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lengthInSamples" eType="#//UnsignedInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRepeats" eType="#//UnsignedInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChunkDataListTypeID">
    <eLiterals name="UNKNOWN" value="-1" literal="Unknown"/>
    <eLiterals name="ADTL" value="1819567201" literal="Associated Data Type List - 'adtl'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChunkTypeID">
    <eLiterals name="UNKNOWN" value="-1" literal="Unknown Chunk"/>
    <eLiterals name="RIFF" value="1179011410" literal="RIFF Header Chunk - 'RIFF'"/>
    <eLiterals name="WAVE" value="1163280727" literal="WAVE Header Chunk - 'WAVE'"/>
    <eLiterals name="CUE_" value="543520099" literal="Cue Chunk - 'cue '"/>
    <eLiterals name="DATA" value="1635017060" literal="Data Chunk - 'data'"/>
    <eLiterals name="FACT" value="1952670054" literal="Fact Chunk - 'fact'"/>
    <eLiterals name="FMT_" value="544501094" literal="Format Chunk - 'fmt '"/>
    <eLiterals name="INST" value="1953721961" literal="Instrument Chunk - 'inst'"/>
    <eLiterals name="LABL" value="1818386796" literal="Label Chunk - 'labl'"/>
    <eLiterals name="LIST" value="1953720684" literal="Data List Chunk - 'list'"/>
    <eLiterals name="LTXT" value="1954051180" literal="Labeled Text Chunk - 'ltxt'"/>
    <eLiterals name="NOTE" value="1702129518" literal="Note Chunk - 'note'"/>
    <eLiterals name="PLST" value="1953721456" literal="Playlist Chunk - 'plst'"/>
    <eLiterals name="SINT" value="1953393779" literal="Silent Chunk - 'slnt'"/>
    <eLiterals name="SMPL" value="1819307379" literal="Sampler Chunk - 'smpl'"/>
    <eLiterals name="WAVL" value="1819697527" literal="Wave List Chunk - 'wavl'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompressionCode">
    <eLiterals name="COMPRESSION_CODE_0" literal="Unknown"/>
    <eLiterals name="COMPRESSION_CODE_1" value="1" literal="PCM/uncompressed"/>
    <eLiterals name="COMPRESSION_CODE_2" value="2" literal="Microsoft ADPCM"/>
    <eLiterals name="COMPRESSION_CODE_6" value="6" literal="ITU G.711 a-law"/>
    <eLiterals name="COMPRESSION_CODE_7" value="7" literal="ITU G.711 Au-law"/>
    <eLiterals name="COMPRESSION_CODE_17" value="17" literal="IMA ADPCM"/>
    <eLiterals name="COMPRESSION_CODE_20" value="20" literal="ITU G.723 ADPCM (Yamaha)"/>
    <eLiterals name="COMPRESSION_CODE_49" value="49" literal="GSM 6.10"/>
    <eLiterals name="COMPRESSION_CODE_64" value="64" literal="ITU G.721 ADPCM"/>
    <eLiterals name="COMPRESSION_CODE_80" value="80" literal="MPEG"/>
    <eLiterals name="COMPRESSION_CODE_65536" value="65536" literal="Experimental"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SampleLoopType">
    <eLiterals name="UNKNOWN" value="-1" literal="Unknown"/>
    <eLiterals name="FORWARD" literal="Loop Forward (normal)"/>
    <eLiterals name="PING_PONG" value="1" literal="Alternating loop (forward/backward, also known as Ping Pong)"/>
    <eLiterals name="BACKWARD" value="2" literal="Loop backward (reverse)"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SMPTEFormat">
    <eLiterals name="SMPTE_0" literal="no SMPTE offset"/>
    <eLiterals name="SMPTE_24" value="24" literal="24 frames per second"/>
    <eLiterals name="SMPTE_25" value="25" literal="25 frames per second"/>
    <eLiterals name="SMPTE_29" value="29" literal="30 frames per second with frame dropping (30 drop)"/>
    <eLiterals name="SMPTE_30" value="30" literal="30 frames per second"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AudioFileFormat" instanceClassName="javax.sound.sampled.AudioFileFormat"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AudioFormat" instanceClassName="javax.sound.sampled.AudioFormat"/>
  <eClassifiers xsi:type="ecore:EDataType" name="AudioInputStream" instanceClassName="javax.sound.sampled.AudioInputStream"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ExtendedByteBuffer" instanceClassName="com.skratchdot.riff.wav.util.ExtendedByteBuffer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IOException" instanceClassName="java.io.IOException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="RiffWaveException" instanceClassName="com.skratchdot.riff.wav.util.RiffWaveException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UnsignedShort" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UnsignedInt" instanceClassName="java.lang.Long"/>
  <eClassifiers xsi:type="ecore:EDataType" name="UnsupportedAudioFileException" instanceClassName="javax.sound.sampled.UnsupportedAudioFileException"/>
</ecore:EPackage>
